language: python
cache: pip
sudo: required
services:
  - docker
os:
  - linux
env:
  - BOTO_CONFIG=/dev/null
python:
  - "3.6"
script:
  - pip install -U pip pipenv
  - pipenv install --dev
  - pipenv run pytest --cov=arxiv --cov=announcement/announcement --cov=repository/repository --cov-report=term-missing arxiv announcement/announcement repository/repository
after_success:
  - pipenv run -m coveralls
  - "./tests/lint.sh arxiv"
  - "./tests/lint.sh announcement/announcement"
  - "./tests/lint.sh repository/repository"
  - "./tests/style.sh arxiv"
  - "./tests/style.sh announcement/announcement"
  - "./tests/style.sh repository/repository"
  - "./tests/type-check.sh arxiv"
  - "./tests/type-check.sh announcement/announcement"
  - "./tests/type-check.sh repository/repository"